spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/entity_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import:
      - "application-prd.yaml"
server:
  port: 8080

build:
  version: "3.0.0"

auth:
  message: "Welcome to compliant service related local apis"
  contactDetails:
    name: "Suresh - Developer"
    email: "suresh@dev.com"
  onCallSupport:
    - 9876543210
    - 1234567890
